# Generated by Django 3.1.7 on 2021-02-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
