# Generated by Django 3.1.7 on 2021-02-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210220_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_date',
            new_name='updated',
        ),
    ]
